---
title: "Multiplicity"
subtitle: "p3003 Proteome Bioinformatics Course"
author: "Witek Wolski"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.dim=c(4.8, 4.5), fig.retina=2, out.width="100%")
knitr::opts_hooks$set(fig.callout = function(options) {
  if (options$fig.callout) {
    options$echo <- FALSE
    options$out.height <- "99%"
    options$fig.width <- 16
    options$fig.height <- 8
  }
  options
})
```



```{css, echo=FALSE}
/* custom.css */
  .left-code {
    color: #777;
      width: 38%;
    height: 92%;
    float: left;
  }
.right-plot {
  width: 60%;
  float: right;
  padding-left: 1%;
}
.plot-callout {
  height: 225px;
  width: 450px;
  bottom: 5%;
  right: 5%;
  position: absolute;
  padding: 0px;
  z-index: 100;
}
.plot-callout img {
  width: 100%;
  border: 4px solid #23373B;
}
```


# Simulate some data


Do some slides illustrating this.
Idea is to simulate some data and than fit various models to obtain those distribution shown and discussed here:

(interpreting-pvalue-histogram)[http://varianceexplained.org/statistics/interpreting-pvalue-histogram/]



```{r}



```
